### ISSUE TITLE
Requiring several functions?

### ISSUE THREAD

**Issue by gdalle** [Seelengrab/RequiredInterfaces.jl#1]
Awesome package, it's simple enough to use that I wanna give it a test run in HMMs.jl!

Small question: how does one specify that multiple functions are part of the interface?
My two best guesses are
```julia
@required T f(::T) g(::T)
```
or
```julia
@required T f(::T)
@required T g(::T)
```
Judging by the code I'm leaning towards option 2 but I'm not a macro expert. Also, it may be cool to allow option 1?

**Comment by Seelengrab** [comment]
Yes, option two is currently the only way. I haven't thought about making option one work, but I'm a bit hesitant to add that because I think the lines are going to get very long very quick; especially with a bit longer function names and more than one argument.

Adding an example with more than one function would be good though!

**Comment by Seelengrab** [comment]
Would something like

```julia
@required MyInterface begin
    f(...)
    g(...)
end
```

Work for you?

**Comment by gdalle** [comment]
Yes that's perfect :)
