### ISSUE TITLE
Interface for callable struct

### ISSUE THREAD

**Issue by BatyLeo** [Seelengrab/RequiredInterfaces.jl#11]
I can't seem to find a syntax that works, is it possible to directly use `@required` for the callable method of a callable struct?
Currently I'm only able to do it through an intermediate method like this:
```julia
using RequiredInterfaces
using Test
const RI = RequiredInterfaces

abstract type A end

(a::A)(x) = call(a, x)

@required A begin
    call(a::A, x)
end

struct B <: A end

call(b::B, x) = 0.0
```

instead of:
```julia
using RequiredInterfaces
using Test
const RI = RequiredInterfaces

abstract type A end

@required A begin
    (a::A)(x)
end

struct B <: A end

(b::B)(x) = 0.0
```

**Comment by Seelengrab** [comment]
Good catch! I hadn't thought of that usecase. The macro is actually only choking on this because I just take the first part of the `:call` expression and naively use that, which doesn't work anymore if that itself is a `::` expression as well.

The fix would be to special case this here, explicitly checking whether this is a symbol or an `a::A` kind of expression:

https://github.com/Seelengrab/RequiredInterfaces.jl/blob/f159df317bd82d1f174c58b48205f8600591947e/src/RequiredInterfaces.jl#L72C15-L72C15

This may have some implications on how this is checked for - RequiredInterfaces.jl currently uses `methods` internally for its checking, which requires an instance of `A` (or `B`) in order to query the callable methods for it.. I'll have to see how this can be accommodated without requiring an instance of `B`.

**Comment by Seelengrab** [comment]
This has been implemented in https://github.com/Seelengrab/RequiredInterfaces.jl/commit/6644a95dd5c0f9b8891631ce318c0b2687d58035
