### ISSUE TITLE
Require a function that takes a type as input

### ISSUE THREAD

**Issue by stelmo** [Seelengrab/RequiredInterfaces.jl#13]
A package I am developing has an abstract type with a load function that all subtypes should implement. This load function usually looks like this: `load(::Type{B}, path::String)`, where `B <: A` and `A` is the abstract type. The point of this style of function is to use dispatch construct the appropriate model from a file. Is there a way to use your package to enforce this interface? Currently I get this error when I try:
```julia
julia> using RequiredInterfaces

julia> abstract type A end

julia> function f end
f (generic function with 0 methods)

julia> @required A f(::Type{A})
ERROR: LoadError: MethodError: Cannot `convert` an object of type Expr to an object of type Symbol

Closest candidates are:
  convert(::Type{T}, ::T) where T
   @ Base Base.jl:64
  Symbol(::Any...)
   @ Base strings\basic.jl:229

Stacktrace:
 [1] setindex!(A::Vector{Symbol}, x::Expr, i1::Int64)
   @ Base .\array.jl:969
 [2] var"@required"(__source__::LineNumberNode, __module__::Module, T::Symbol, expr::Expr)
   @ RequiredInterfaces C:\Users\stelmo\.julia\packages\RequiredInterfaces\7J9AU\src\RequiredInterfaces.jl:70
in expression starting at REPL[7]:1
```
All other functions/dispatches work very nicely :)

**Comment by Seelengrab** [comment]
So the more general request behind this specific feature is "allowing to place the interface type in type parameter position in a signature". This is a bit tricky, because that is (in general) not a safe interface requirement, because the type parameters of any given type are (generally) not part of the extensible interface of that type. For example, it's illegal to define `size(::Vector{MyType})` when you don't own `Vector`, even though you own `MyType`; the `size <-> Vector` coupling trumps the `size <-> MyType` coupling. 

`Type` in your request is a special case, in that this is the only way to make this kind of dispatch work; even though `Base` (or even `Core`) is the one to own that type. It may be that the crucial difference is that unlike `size(::Vector)`, there isn't already a `myfoo(::Type)` defined from Base; but this is something that needs to be carefully examined first.

**Comment by exaexa** [comment]
Hi all,
just adding a few possibly motivating use-cases:
- `zero(::Type{MyNumber})`  -- "must provide a zero"
- `zeros`, `ones` and similar algebra-ish things for algebra-ish types
- `convert(::Type{MyThing}, xxx::X)`   -- must provide a conversion from X

**Comment by Seelengrab** [comment]
Yeah, it's definitely a common thing to dispatch on. Might be worth special casing for now, before trying to tackle the general case (if that is sensible to do, which I haven't decided yet).

**Comment by exaexa** [comment]
> general cacse

No I don't think general case is very suitable now; AFAIK there isn't any guarantee on whether the type parameters are sufficiently covariant with `<:` to allow decision on whether the overload is hijacking something or not.

> Typical case with `::Type{X}`

I guess add that as a special case here https://github.com/Seelengrab/RequiredInterfaces.jl/blob/main/src/RequiredInterfaces.jl#L70 and below might just work? (my julia-fu is currently insufficient to read the `ntuple(...) do ...` around L76, so it might be there too)

**Comment by Seelengrab** [comment]
> I guess add that as a special case here

Yes, that's one part - it also needs to be handled specially in the checking code below. Ironically, the "easy" way of doing that is to add support for all kinds of type parameter shenanigans, but then only limit it to `Type` when constructing the `Interface` :joy:

**Comment by Seelengrab** [comment]
For reference, this was implemented in https://github.com/Seelengrab/RequiredInterfaces.jl/commit/83a68e80ad8117bf22c9b77b036258c511144352

**Comment by stelmo** [comment]
Thank you very much for implementing this!

**Comment by Seelengrab** [comment]
You're welcome!
