### ISSUE TITLE
LTS compat

### ISSUE THREAD

**Issue by gdalle** [Seelengrab/RequiredInterfaces.jl#3]
How hard would it be to lower the compat bound to Julia 1.6?

**Comment by Seelengrab** [comment]
It's possible in principle - the issue is that [this function](https://github.com/Seelengrab/RequiredInterfaces.jl/blob/af7bbcf783ba8daf1643ad7373f533714f4c61fe/src/RequiredInterfaces.jl#L216) relies on way too many internals. So supporting a julia version means writing special code for each version, mostly by manually matching what exactly `code_typed` returns.

I'd love for this to go through supported API, but alas, I don't know of an API checking for an exact error (in terms of the `NotImplementedError` type in this package) without actually calling the method. Perhaps something is possible with a custom abstract interpreter?

**Comment by gdalle** [comment]
The thing is, if you only start compat at 1.9, no established package can use yours... except maybe as a weakdep? I'll give it a try and report back.

> I don't know of an API checking for an exact error

Do you need to check the exact error? Or would any error do?

**Comment by Seelengrab** [comment]
> The thing is, if you only start compat at 1.9, no established package can use yours for fear of breaking lower Julia support.  

Yes, that is true - please don't misunderstand, I recognize the issue, I just haven't had time to go that far back & test it out. I already ran into an issue due to originally developing on 1.10-dev.

Knowing where/how/if it fails on 1.6 would already be a big boon though!

> Plus the trouble will start again for 1.10 and beyond...

For future versions, I can luckily add support as they are released/once the current code breaks :) So that's less of an issue.

> Do you need to check the exact error? Or would any error do?

The issue is that I can't guarantee the semantics of errors other than the one from this package, even if they're called the same!

**Comment by gdalle** [comment]
> I recognize the issue, I just haven't had time to go that far back & test it out.

No worries, it was not an urgent request or anything :) It would actually be cool if one could specify dependencies that are activated or not depending on the Julia version. I ran into similar problems with JET and Aqua.

> For future versions, I can luckily add support as they are released/once the current code breaks :)

If it ain't broke don't fix it, right 😎 ?

**Comment by gdalle** [comment]
> Knowing where/how/if it fails on 1.6 would already be a big boon though!

Your wish is my command

https://github.com/Seelengrab/RequiredInterfaces.jl/pull/4

**Comment by gdalle** [comment]
I figured out a way around this:
- Use RequiredInterfaces.jl in an [extension](https://pkgdocs.julialang.org/v1/creating-packages/#Conditional-loading-of-code-in-packages-(Extensions)) but [without supporting older Julia versions](https://pkgdocs.julialang.org/v1/creating-packages/#Using-an-extension-while-supporting-older-Julia-versions). This goes in `Project.toml`:
```toml
[deps]
# don't put RequiredInterfaces here

[weakdeps]
RequiredInterfaces = "97f35ef4-7bc5-4ec1-a41a-dcc69c7308c6"

[extensions]
MyPackageRequiredInterfacesExt = "RequiredInterfaces"

[compat]
RequiredInterfaces = "0.1"

[extras]
RequiredInterfaces = "97f35ef4-7bc5-4ec1-a41a-dcc69c7308c6"

[targets]
test = [] # don't put RequiredInterfaces here

```
- Put the following code in the extension module `ext/MyPackageRequiredInterfacesExt.jl`
```julia

module MyPackageRequiredInterfacesExt

using MyPackage
using RequiredInterfaces: @required

@required MyType begin
    Base.length(::MyType)
    MyPackage.myfunc(::MyType)
end

end
```
- Install and uninstall the package when testing the interface, by putting this in `test/interface.jl`
```julia
using Pkg
Pkg.add(;
    url="https://github.com/Seelengrab/RequiredInterfaces.jl", rev="feat/multifunc_required"
)

using RequiredInterfaces
using MyPackage
using Test

RequiredInterfaces.check_interface_implemented(MyType, MyStruct)

Pkg.rm("RequiredInterfaces")
```
- Only include `test/interface.jl` on version 1.9 and above, thanks to this block in `test/runtests.jl`:
```julia
@testset verbose = true "MyPackage.jl" begin
    # usual tests

    if VERSION >= v"1.9"
        @testset "Interface" begin
            include("interface.jl")
        end
    end
end

```
